#!/bin/bash

echo "================================================"
echo "Gmail Integration Setup Guide"
echo "================================================"
echo ""
echo "📋 Google Cloud Console Configuration Steps:"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo ""
echo "2. Enable Gmail API:"
echo "   - Navigate to 'APIs & Services' > 'Library'"
echo "   - Search for 'Gmail API'"
echo "   - Click 'Enable'"
echo ""
echo "3. Configure OAuth Consent Screen:"
echo "   - Go to 'APIs & Services' > 'OAuth consent screen'"
echo "   - Choose 'External' user type"
echo "   - Fill in app name: 'NextQuark Mail'"
echo "   - Add support email"
echo "   - Add scopes: https://www.googleapis.com/auth/gmail.modify"
echo "   - Add test users (your Gmail accounts)"
echo ""
echo "4. Configure OAuth 2.0 Client:"
echo "   - Go to 'APIs & Services' > 'Credentials'"
echo "   - Click on your OAuth 2.0 Client ID"
echo "   - Add Authorized redirect URIs:"
echo ""
echo "   For Expo Development:"
echo "   https://auth.expo.io/@YOUR_EXPO_USERNAME/hireswipe-v3-clone-ceuofke"
echo ""
echo "   For Custom Scheme:"
echo "   rork-app://"
echo ""
echo "   For Web:"
echo "   http://localhost:8081"
echo "   https://localhost:8081"
echo ""
echo "5. Your OAuth Credentials:"
echo "   Configure these in your .env file:"
echo "   EXPO_PUBLIC_GOOGLE_CLIENT_ID=<your-client-id>"
echo "   EXPO_PUBLIC_GOOGLE_CLIENT_SECRET=<your-client-secret>"
echo ""
echo "================================================"
echo "📱 Testing the Integration:"
echo "================================================"
echo ""
echo "1. Start the app:"
echo "   bun run start"
echo ""
echo "2. Open the Messages tab"
echo ""
echo "3. Tap 'Connect Gmail Account'"
echo ""
echo "4. Sign in with your Google account"
echo ""
echo "5. Grant permissions"
echo ""
echo "6. Your Gmail inbox will load!"
echo ""
echo "================================================"
echo "✅ Features Available:"
echo "================================================"
echo ""
echo "✓ View inbox, sent, starred emails"
echo "✓ Search and filter emails"
echo "✓ Star/unstar emails"
echo "✓ Delete emails (move to trash)"
echo "✓ Archive emails"
echo "✓ Mark as read/unread"
echo "✓ Reply and forward emails"
echo "✓ Rich text formatting"
echo "✓ Push notifications (every 2 minutes)"
echo "✓ Notification tap to open email"
echo ""
echo "================================================"
echo "🔔 Notification Setup:"
echo "================================================"
echo ""
echo "Notifications are automatically configured!"
echo "- Checks for new emails every 2 minutes"
echo "- Shows sender, subject, and preview"
echo "- Tap notification to open email"
echo ""
echo "To test notifications:"
echo "1. Keep the app running in background"
echo "2. Send yourself a test email"
echo "3. Wait up to 2 minutes"
echo "4. You'll receive a notification!"
echo ""
echo "================================================"
echo "Done! 🚀"
echo "================================================"
