import React from 'react';
import { MaterialCommunityIcons, Ionicons, FontAwesome5, FontAwesome, Feather, MaterialIcons } from '@expo/vector-icons';

type IconProps = { size?: number; color?: string; strokeWidth?: number; style?: any; fill?: string };

const BUMP = 2;
const icon = (Comp: any, name: string) => ({ size = 24, color = '#000', style, ...rest }: IconProps) => (
  <Comp name={name} size={size + BUMP} color={color} style={style} />
);

export const ChevronRight = icon(MaterialCommunityIcons, 'chevron-right');
export const ChevronDown = icon(MaterialCommunityIcons, 'chevron-down');
export const Briefcase = icon(MaterialCommunityIcons, 'briefcase-outline');
export const GraduationCap = icon(MaterialCommunityIcons, 'school-outline');
export const Star = icon(MaterialCommunityIcons, 'star');
export const Eye = icon(MaterialCommunityIcons, 'eye-outline');
export const FileText = icon(MaterialCommunityIcons, 'file-document-outline');
export const LogOut = icon(MaterialCommunityIcons, 'logout');
export const Zap = icon(MaterialCommunityIcons, 'lightning-bolt');
export const Plus = icon(MaterialCommunityIcons, 'plus');
export const X = icon(MaterialCommunityIcons, 'close');
export const Check = icon(MaterialCommunityIcons, 'check');
export const Pencil = icon(MaterialCommunityIcons, 'pencil');
export const Camera = icon(MaterialCommunityIcons, 'camera');
export const MapPin = icon(MaterialCommunityIcons, 'map-marker-outline');
export const Award = icon(MaterialCommunityIcons, 'medal-outline');
export const Link2 = icon(MaterialCommunityIcons, 'link-variant');
export const Crown = icon(MaterialCommunityIcons, 'crown');
export const Phone = icon(MaterialCommunityIcons, 'phone-outline');
export const Mail = icon(MaterialCommunityIcons, 'email-outline');
export const Github = icon(MaterialCommunityIcons, 'github');
export const Linkedin = icon(MaterialCommunityIcons, 'linkedin');
export const Trophy = icon(MaterialCommunityIcons, 'trophy-outline');
export const ShieldCheck = icon(MaterialCommunityIcons, 'shield-check-outline');
export const Settings = icon(Ionicons, 'settings-outline');
export const Share2 = icon(MaterialCommunityIcons, 'share-variant-outline');
export const Lock = icon(MaterialCommunityIcons, 'lock-outline');
export const Gift = icon(MaterialCommunityIcons, 'gift-outline');
export const FileCheck = icon(MaterialCommunityIcons, 'file-check-outline');
export const Search = icon(Ionicons, 'search');
export const Moon = icon(Ionicons, 'moon-outline');
export const Sun = icon(Ionicons, 'sunny-outline');
export const Contact = icon(MaterialCommunityIcons, 'card-account-details-outline');
export const Heart = icon(MaterialCommunityIcons, 'heart-outline');
export const Target = icon(MaterialCommunityIcons, 'target');
export const Building2 = icon(MaterialCommunityIcons, 'office-building-outline');
export const Laptop = icon(MaterialCommunityIcons, 'laptop');
export const Sparkles = icon(MaterialCommunityIcons, 'auto-fix');
export const ScrollText = icon(MaterialCommunityIcons, 'script-text-outline');
export const BadgeCheck = icon(MaterialCommunityIcons, 'certificate-outline');
export const Scale = icon(MaterialCommunityIcons, 'scale-balance');
export const Rocket = icon(MaterialCommunityIcons, 'rocket-launch-outline');
export const TrendingUp = icon(MaterialCommunityIcons, 'trending-up');
export const Bookmark = icon(MaterialCommunityIcons, 'bookmark-outline');
export const FolderOpen = icon(MaterialCommunityIcons, 'folder-open-outline');
export const Upload = icon(MaterialCommunityIcons, 'upload');
export const ExternalLink = icon(MaterialCommunityIcons, 'open-in-new');
export const Trash2 = icon(MaterialCommunityIcons, 'trash-can-outline');
export const ArrowLeft = icon(MaterialCommunityIcons, 'arrow-left');
export const Wifi = icon(MaterialCommunityIcons, 'wifi');
export const Globe = icon(MaterialCommunityIcons, 'earth');
export const Shield = icon(MaterialCommunityIcons, 'shield-outline');
export const Users = icon(MaterialCommunityIcons, 'account-group-outline');
export const AlertCircle = icon(MaterialCommunityIcons, 'alert-circle-outline');
export const Archive = icon(MaterialCommunityIcons, 'archive-outline');
export const Copy = icon(MaterialCommunityIcons, 'content-copy');
export const Forward = icon(MaterialCommunityIcons, 'share-outline');
export const Inbox = icon(MaterialCommunityIcons, 'inbox');
export const MailOpen = icon(MaterialCommunityIcons, 'email-open-outline');
export const Menu = icon(MaterialCommunityIcons, 'menu');
export const Paperclip = icon(MaterialCommunityIcons, 'paperclip');
export const RefreshCw = icon(MaterialCommunityIcons, 'refresh');
export const Reply = icon(MaterialCommunityIcons, 'reply');
export const Send = icon(MaterialCommunityIcons, 'send');
export const Strikethrough = icon(MaterialCommunityIcons, 'format-strikethrough');
export const Underline = icon(MaterialCommunityIcons, 'format-underline');
export const Clock = icon(MaterialCommunityIcons, 'clock-outline');
export const HelpCircle = icon(MaterialCommunityIcons, 'help-circle-outline');
export const Info = icon(MaterialCommunityIcons, 'information-outline');
export const MessageSquareMore = icon(MaterialCommunityIcons, 'message-text-outline');
export const Lightbulb = icon(MaterialCommunityIcons, 'lightbulb-outline');
export const Twitter = icon(MaterialCommunityIcons, 'twitter');
export const Instagram = icon(MaterialCommunityIcons, 'instagram');
export const BookOpen = icon(MaterialCommunityIcons, 'book-open-variant');
export const DollarSign = icon(MaterialCommunityIcons, 'currency-usd');
